name: Rearch
description: Research
title: "[Rearch]: "
labels: [research]
body:
  - type: textarea
    attributes:
      label: Background
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "?"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Achieve
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "?"
    validations:
      required: true
  - type: markdown
    id: Todo
    attributes:
      value: |
        "- [ ]"
