name: Rearch
description: Research
title: "[Rearch]: "
labels: [research]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: markdown
    id: background
    attributes:
      label: background
      description: Write background
      placeholder: "_"
    validations:
      required: true
  - type: markdown
    id: 
    attributes:
      label: achieve
      description: What you want to achieve.
      placeholder: "_"
    validations:
      required: true
  - type: markdown
    id: todo
    attributes:
      label: TODO
      description: TODO
      value: "- [ ] "
