name: Rearch
description: Research
title: "[Rearch]: "
labels: [research]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: markdown
    id: background
    attributes:
      value: Background
    validations:
      required: true
  - type: markdown
    id: 
    attributes:
      value: "Achieve"
    validations:
      required: true
  - type: markdown
    id: Todo
    attributes:
      value: |
        "- [ ]"
