name: Report
description: Report
title: "[Report] "
labels: [report]
body:
  - type: textarea
    attributes:
      label: Abstract or TableContents
      description: What do you want to tell?
      placeholder: Tell us what you see!
      value: "?"
    validations:
      required: true
  - type: textarea
    attributes:
      label: References
      description: What urls are interested in?
      placeholder: Write URLs
      value: |
        - 
    validations:
      required: false
