name: Research
description: Research
title: "[Research] "
labels: [research]
body:
  - type: textarea
    attributes:
      label: Background
      description: Why research?, What Problem?
      placeholder: Tell us what you see!
      value: "?"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Goals
      description: What achieve?
      placeholder: Tell us what you see!
      value: "?"
    validations:
      required: true
  - type: textarea
    attributes:
      label: TODO
      description: TODO List
      value: |
        - [ ] 参考資料の収集
        - [ ] 情報選別
        - [ ] 結論
    validations:
      required: true
