name: Scrap Trouble
description: Little Trouble
title: "[Scrap Trouble] "
labels: [report]
body:
  - type: textarea
    attributes:
      label: Problem
      description: What trouble?
      placeholder: Tell us what you see!
      value: "?"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Cause
      description: Why caurse?
      placeholder: Tell us what you see!
      value: "?"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Solution
      description: Solution
      value: |
        - 
    validations:
      required: false
