name: Study
description: Study
title: "[Study] "
labels: [study]
body:
  - type: textarea
    attributes:
      label: Background
      description: Why study?
      placeholder: Tell us what you see!
      value: "?"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Target
      description: What study?
      placeholder: Tell us what you see!
      value: "?"
    validations:
      required: true
  - type: textarea
    attributes:
      label: References
      description: References
      value: |
        - [ ] 
    validations:
      required: true
